apiVersion: v1
kind: Secret
metadata:
  name: ckancredentials
type: Opaque

stringData:
  sysadminPassword: {{ .Values.ckan.env.sysadminPassword }}
  psqlMasterPassword: {{ .Values.ckan.env.psql.masterPassword }}
{{if .Values.ckan.env.psql.runOnAzure }}
  ckanSqlAlchemyUrl: "postgresql://{{ .Values.ckan.env.db.ckanDbUser }}@{{ .Values.ckan.env.db.ckanDbUrl }}:{{ .Values.ckan.env.db.ckanDbPassword }}@{{ .Values.ckan.env.db.ckanDbUrl }}/{{ .Values.ckan.env.db.ckanDbName }}"
{{else }}
  ckanSqlAlchemyUrl: "postgresql://{{ .Values.ckan.env.db.ckanDbUser }}:{{ .Values.ckan.env.db.ckanDbPassword }}@{{ .Values.ckan.env.db.ckanDbUrl }}/{{ .Values.ckan.env.db.ckanDbName }}"
{{end }}
