apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/psql"