apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
